/**
 * @link https://www.iana.org/assignments/media-types/media-types.xhtml List of All Official MIME Types
 * @link https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types List of Common MIME Types
 */
const MimeType = {
    APPLICATION_GZIP: 'application/gzip',
    APPLICATION_JAVA_ARCHIVE: 'application/java-archive',
    APPLICATION_JSON: 'application/json',
    APPLICATION_MSWORD: 'application/msword',
    APPLICATION_OCTET_STREAM: 'application/octet-stream',
    APPLICATION_OGG: 'application/ogg',
    APPLICATION_PDF: 'application/pdf',
    APPLICATION_RTF: 'application/rtf',
    APPLICATION_XML: 'application/xml',
    APPLICATION_ZIP: 'application/zip',
    AUDIO_3_GPP: 'audio/3gpp',
    AUDIO_3_GPP_2: 'audio/3gpp2',
    AUDIO_AAC: 'audio/aac',
    AUDIO_MPEG: 'audio/mpeg',
    AUDIO_OGG: 'audio/ogg',
    AUDIO_OPUS: 'audio/opus',
    AUDIO_WAV: 'audio/wav',
    AUDIO_WEBM: 'audio/webm',
    AUDIO_X_MIDI: 'audio/x-midi',
    FONT_OTF: 'font/otf',
    FONT_TTF: 'font/ttf',
    FONT_WOFF: 'font/woff',
    FONT_WOFF_2: 'font/woff2',
    IMAGE_AVIF: 'image/avif',
    IMAGE_BMP: 'image/bmp',
    IMAGE_GIF: 'image/gif',
    IMAGE_JPEG: 'image/jpeg',
    IMAGE_PNG: 'image/png',
    IMAGE_SVG_XML: 'image/svg+xml',
    IMAGE_TIFF: 'image/tiff',
    IMAGE_WEBP: 'image/webp',
    TEXT_CALENDAR: 'text/calendar',
    TEXT_CSS: 'text/css',
    TEXT_CSV: 'text/csv',
    TEXT_HTML: 'text/html',
    TEXT_JAVASCRIPT: 'text/javascript',
    TEXT_PLAIN: 'text/plain',
    VIDEO_3_GPP: 'video/3gpp',
    VIDEO_3_GPP_2: 'video/3gpp2',
    VIDEO_MP_2_T: 'video/mp2t',
    VIDEO_MP_4: 'video/mp4',
    VIDEO_MPEG: 'video/mpeg',
    VIDEO_OGG: 'video/ogg',
    VIDEO_WEBM: 'video/webm',
    VIDEO_X_MSVIDEO: 'video/x-msvideo'
};

export default Object.freeze(MimeType);
